# Generated by Django 3.0.5 on 2020-04-16 05:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(10)])),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.TextField()),
                ('company_phone', models.CharField(max_length=9, unique=True)),
                ('contract_fname', models.CharField(max_length=255)),
                ('contract_lname', models.CharField(max_length=255)),
                ('expires_date', models.DateField()),
                ('other_notes', models.TextField()),
                ('account_acc_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dep_id', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(10)])),
                ('dep_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('days_left', models.IntegerField(auto_created=5, max_length=10)),
                ('emp_id', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(10)])),
                ('entrance_date', models.DateField()),
                ('leave_date', models.DateField()),
                ('salary', models.FloatField()),
                ('bonus', models.FloatField()),
                ('reimburse', models.FloatField()),
                ('account_acc_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department_dep_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('manag_id', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(10)])),
                ('manag_fname', models.CharField(max_length=255)),
                ('manag_lname', models.CharField(max_length=255)),
                ('manag_level', models.IntegerField(max_length=10)),
                ('manag_phone', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Accountant',
            fields=[
                ('position', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('employee_emp_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='management.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('position', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('employee_emp_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='management.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(10)])),
                ('store_name', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
                ('cost_total', models.FloatField()),
                ('repaired', models.CharField(max_length=255)),
                ('other_notes', models.TextField()),
                ('company_company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Company')),
                ('manage_manag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Manager')),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('cost_id', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(10)])),
                ('electric_bill', models.FloatField()),
                ('water_bill', models.FloatField()),
                ('rent_fee', models.FloatField()),
                ('repair_fee', models.FloatField()),
                ('insurance_fee', models.FloatField()),
                ('other_fee', models.FloatField()),
                ('date', models.DateField()),
                ('store_store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Store')),
                ('accountant_employee_emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Accountant')),
            ],
        ),
        migrations.CreateModel(
            name='Aperture',
            fields=[
                ('aper_id', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(10)])),
                ('aper_area', models.FloatField()),
                ('aper_loc', models.CharField(max_length=255)),
                ('aper_price', models.FloatField()),
                ('aper_status', models.BooleanField()),
                ('issue_date', models.DateField(auto_now=True)),
                ('store_store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Store')),
                ('sale_employee_emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Sale')),
            ],
        ),
    ]
