# Generated by Django 3.0.5 on 2020-04-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20200416_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bonus',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='leave_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='reimburse',
            field=models.FloatField(null=True),
        ),
    ]
