# Generated by Django 3.0.5 on 2020-04-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20200418_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountant',
            name='emp_type',
            field=models.CharField(choices=[('ACC', 'Accountant'), ('SALE', 'Sale')], default='ACC', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='acc_type',
            field=models.CharField(choices=[('EMP', 'Employee'), ('COM', 'Company')], default='COM', max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='acc_type',
            field=models.CharField(choices=[('EMP', 'Employee'), ('COM', 'Company')], default='EMP', max_length=255),
        ),
        migrations.AddField(
            model_name='sale',
            name='emp_type',
            field=models.CharField(choices=[('ACC', 'Accountant'), ('SALE', 'Sale')], default='SALE', max_length=255),
        ),
    ]
