# Generated by Django 3.0.5 on 2020-04-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20200419_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='aperture',
            name='aper_pic',
            field=models.ImageField(default=None, upload_to='C:/Users/LilAop/Desktop/django_projects/Reserve_Aperture_System/static/img_aper'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_pic',
            field=models.ImageField(default=None, upload_to='C:/Users/LilAop/Desktop/django_projects/Reserve_Aperture_System/static/img_store'),
        ),
    ]
