# Generated by Django 3.0.5 on 2020-04-23 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20200423_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aperture',
            name='store_store_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Store'),
        ),
    ]
