# Generated by Django 3.0.4 on 2020-04-24 02:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_auto_20200423_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aperture',
            name='aper_pic',
            field=models.ImageField(default=None, upload_to='C:/Users/Puntakarn/Desktop/Django_Projects/Reserve_Aperture_System/media'),
        ),
        migrations.AlterField(
            model_name='company',
            name='expires_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 24, 9, 56, 5, 879503)),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_pic',
            field=models.ImageField(default=None, upload_to='C:/Users/Puntakarn/Desktop/Django_Projects/Reserve_Aperture_System/media'),
        ),
    ]
