# Generated by Django 3.0.5 on 2020-04-24 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_auto_20200424_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='expires_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 24, 18, 49, 35, 594036)),
        ),
    ]
