# Generated by Django 3.0.5 on 2020-04-25 04:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_auto_20200424_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aperture',
            name='aper_pic',
            field=models.ImageField(default=None, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='company',
            name='expires_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 25, 11, 31, 9, 36196)),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_pic',
            field=models.ImageField(default=None, upload_to='media'),
        ),
    ]
