# Generated by Django 3.0.5 on 2020-04-25 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_auto_20200425_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='manager_manag_id',
        ),
        migrations.AlterField(
            model_name='company',
            name='expires_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 25, 14, 36, 12, 602728)),
        ),
        migrations.AlterField(
            model_name='store',
            name='cost_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='repaired',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
