# Generated by Django 3.0.5 on 2020-04-25 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_auto_20200425_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aperture',
            name='aper_pic',
            field=models.ImageField(default=None, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='expires_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 25, 17, 15, 3, 727558)),
        ),
        migrations.AlterField(
            model_name='cost',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_pic',
            field=models.ImageField(default=None, upload_to='media/'),
        ),
    ]
